alias ls="ls --color=auto --group-directories-first"
alias la="ls -a --color=auto --group-directories-first"
alias ll="ls -al --color=auto --group-directories-first"
alias ..="cd .."
alias vi="vim"
alias ping="ping -c 5"
alias grep="grep -i"
alias ddgr="ddgr -n 7"
